[package]
name = "rowmantic"
version = "0.1.0-rc1"
entrypoint = "src/lib.typ"
authors = ["Ulrik Sverdrup"]
license = "EUPL-1.2"
description = "Define tables row by row with inline separators in content."
repository = "https://github.com/typst-community/rowmantic"

compiler = "0.13.0"
categories = ["components"]
keywords = ["table", "row", "delimiter", "latex"]

exclude = [
  "**.pdf",
  "**.png",
  "*-example.typ",
  "scripts",
  "docs",
  ".github",
  "tests",
  ".typstignore",
  "Justfile",
]
